worker_processes auto;

events {
    worker_connections 1024;
}

http {
    server {
        listen 9000;

        location / {
            lua_socket_log_errors off;
            content_by_lua_file /app/d127e1a304605558.lua;
        }
    }
}
